services:
  backend:
    build: ../backend
    container_name: telemed-backend
    env_file:
      - ../backend/.env
    ports: ["8000:8000"]
    depends_on: [postgres, redis]
    volumes:
      - backend_data:/data

  frontend:
    build: ../frontend
    container_name: telemed-frontend
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8000
    ports: ["3000:3000"]
    depends_on: [backend]

  postgres:
    image: postgres:16
    container_name: telemed-postgres
    env_file:
      - ./.envs/common.env
    ports: ["5432:5432"]
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: telemed-redis
    ports: ["6379:6379"]

volumes:
  pg_data:
  backend_data:
